'##################################################################'
'This Class automatically generated by FeiNz's SQL Class Generator.
'Credit: FeiNz.net [feineriz@live.com]
'##################################################################'

Imports System.Drawing
Imports System.IO
Imports MySql.Data.MySqlClient
Imports System.Windows.Forms

'If this line above is shows error, please download
'[MySQL Connector for .NET] from http://dev.mysql.com/downloads/connector/net/
'and import reference to the project.

Public Class Machine

	'============================== Class Header =============================='

#Region "Class Header"

	Private Shared ConnString As String = "Server=" + My.Settings.Host + ";Database=" + My.Settings.Database + ";Uid=" + My.Settings.Username + ";Pwd=" + My.Settings.Password + ";"
	Private Shared tableName As String = "Machine"

	Private _SQLConn As New MySqlConnection(ConnString)
	Private _CMD As MySqlCommand
	Private _QRY As String

	Shared Function BytesToImage(ByVal ImageBytes() As Byte) As Image

		Dim IMG As Image
		Dim MS As New MemoryStream(ImageBytes)

		IMG = Image.FromStream(MS)
		Return IMG

	End Function

	Shared Function ImageToBytes(ByVal Image As Image) As Byte()

		Dim MS As New MemoryStream
		Dim BT() As Byte

		Image.Save(MS, Image.RawFormat)
		BT = MS.GetBuffer()
		Return BT

	End Function

	Shared Function GetMySQLConnection() As MySqlConnection

		Try
			Dim SQLConn As New MySqlConnection(ConnString)
			SQLConn.Open()
			Return SQLConn

		Catch ex As Exception
			Return Nothing

		End Try

	End Function

	Private _machine_id As Integer
	Private _machine_code As String
	Private _machine_name As String
	Private _detail As String
	Private _remark As String

	Structure MachineInfo
		Dim machine_id As Integer
		Dim machine_code As String
		Dim machine_name As String
		Dim detail As String
		Dim remark As String
	End Structure

	'------------ CONSTRUCTOR ------------'
	Sub New(Machine_machine_id As String, Optional SQLConn As MySqlConnection = Nothing)

		Dim autoCloseConnection As Boolean = False
		If SQLConn Is Nothing Then
			SQLConn = New MySqlConnection(ConnString)
			SQLConn.Open()
			autoCloseConnection = True
		End If

		Dim CMD As MySqlCommand
		Dim RD As MySqlDataReader
		Dim QRY As String

		Try
			QRY = "SELECT *" &
						" FROM " & tableName &
						" WHERE machine_id = '" & Machine_machine_id & "'"

			CMD = New MySqlCommand(QRY, SQLConn)
			RD = CMD.ExecuteReader

			If RD.HasRows Then
				While RD.Read
					_machine_id = RD!machine_id
					_machine_code = RD!machine_code
					_machine_name = RD!machine_name
					_detail = RD!detail
					_remark = RD!remark
				End While
			End If
			If autoCloseConnection Then SQLConn.Close()

		Catch ex As Exception
			If autoCloseConnection Then SQLConn.Close()
			MsgBox("[Error] Sub : Machine.New" & vbCrLf & ex.Message)

		End Try

	End Sub

#End Region

	'============================== Class Properties =============================='

#Region "Class Properties"

	'--- machine_id ---'
	ReadOnly Property machine_id As Integer
		Get
			Return _machine_id
		End Get
	End Property

	'--- machine_code ---'
	Property machine_code As String
		Get
			Return _machine_code
		End Get
		Set(ByVal value As String)
			_QRY = "UPDATE " & tableName &
						 " SET machine_code = '" & value & "'" &
						 " WHERE machine_id = '" & _machine_id & "'"

			Try
				_SQLConn.Open()
				_CMD = New MySqlCommand(_QRY, _SQLConn)
				_CMD.ExecuteNonQuery()
				_SQLConn.Close()

			Catch ex As Exception
				_SQLConn.Close()
				MsgBox("[Error] Property : Machine.machine_code" & vbCrLf & ex.Message, , "Error")

			End Try

			_machine_code = value
		End Set
	End Property

	'--- machine_name ---'
	Property machine_name As String
		Get
			Return _machine_name
		End Get
		Set(ByVal value As String)
			_QRY = "UPDATE " & tableName &
						 " SET machine_name = '" & value & "'" &
						 " WHERE machine_id = '" & _machine_id & "'"

			Try
				_SQLConn.Open()
				_CMD = New MySqlCommand(_QRY, _SQLConn)
				_CMD.ExecuteNonQuery()
				_SQLConn.Close()

			Catch ex As Exception
				_SQLConn.Close()
				MsgBox("[Error] Property : Machine.machine_name" & vbCrLf & ex.Message, , "Error")

			End Try

			_machine_name = value
		End Set
	End Property

	'--- detail ---'
	Property detail As String
		Get
			Return _detail
		End Get
		Set(ByVal value As String)
			_QRY = "UPDATE " & tableName &
						 " SET detail = '" & value & "'" &
						 " WHERE machine_id = '" & _machine_id & "'"

			Try
				_SQLConn.Open()
				_CMD = New MySqlCommand(_QRY, _SQLConn)
				_CMD.ExecuteNonQuery()
				_SQLConn.Close()

			Catch ex As Exception
				_SQLConn.Close()
				MsgBox("[Error] Property : Machine.detail" & vbCrLf & ex.Message, , "Error")

			End Try

			_detail = value
		End Set
	End Property

	'--- remark ---'
	Property remark As String
		Get
			Return _remark
		End Get
		Set(ByVal value As String)
			_QRY = "UPDATE " & tableName &
						 " SET remark = '" & value & "'" &
						 " WHERE machine_id = '" & _machine_id & "'"

			Try
				_SQLConn.Open()
				_CMD = New MySqlCommand(_QRY, _SQLConn)
				_CMD.ExecuteNonQuery()
				_SQLConn.Close()

			Catch ex As Exception
				_SQLConn.Close()
				MsgBox("[Error] Property : Machine.remark" & vbCrLf & ex.Message, , "Error")

			End Try

			_remark = value
		End Set
	End Property

#End Region

	'============================== Required Function =============================='

#Region "Required Function"

	'---------- ADD ----------'
	Shared Function Add(ByVal MachineInfoA As MachineInfo, Optional SQLConn As MySqlConnection = Nothing) As Boolean

		Dim autoCloseConnection As Boolean = False
		If SQLConn Is Nothing Then
			SQLConn = New MySqlConnection(ConnString)
			SQLConn.Open()
			autoCloseConnection = True
		End If

		Dim CMD As MySqlCommand
		Dim QRY As String

		Try
			QRY = "INSERT INTO " & tableName & "(machine_id, machine_code, machine_name, detail, remark)" &
						" VALUES(@machine_id, @machine_code, @machine_name, @detail, @remark)"

			CMD = New MySqlCommand(QRY, SQLConn)

			CMD.Parameters.AddWithValue("@machine_id", MachineInfoA.machine_id)
			CMD.Parameters.AddWithValue("@machine_code", MachineInfoA.machine_code)
			CMD.Parameters.AddWithValue("@machine_name", MachineInfoA.machine_name)
			CMD.Parameters.AddWithValue("@detail", MachineInfoA.detail)
			CMD.Parameters.AddWithValue("@remark", MachineInfoA.remark)

			CMD.ExecuteNonQuery()
			If autoCloseConnection Then SQLConn.Close()

		Catch ex As Exception
			If autoCloseConnection Then SQLConn.Close()
			MsgBox("[Error] Function : Machine.Add" & vbCrLf & ex.Message)
			Return False

		End Try

		Return True

	End Function

	'---------- UPDATE ----------'	
	Shared Function Update(ByVal MachineInfoA As MachineInfo, Optional SQLConn As MySqlConnection = Nothing) As Boolean

		Dim autoCloseConnection As Boolean = False
		If SQLConn Is Nothing Then
			SQLConn = New MySqlConnection(ConnString)
			SQLConn.Open()
			autoCloseConnection = True
		End If

		Dim CMD As MySqlCommand
		Dim QRY As String

		Try
			QRY = "UPDATE " & tableName &
					" SET" &
					" machine_code = @machine_code," &
					" machine_name = @machine_name," &
					" detail = @detail," &
					" remark = @remark" &
					" WHERE machine_id='" & MachineInfoA.machine_id & "'"

			CMD = New MySqlCommand(QRY, SQLConn)

			CMD.Parameters.AddWithValue("@machine_code", MachineInfoA.machine_code)
			CMD.Parameters.AddWithValue("@machine_name", MachineInfoA.machine_name)
			CMD.Parameters.AddWithValue("@detail", MachineInfoA.detail)
			CMD.Parameters.AddWithValue("@remark", MachineInfoA.remark)

			CMD.ExecuteNonQuery()
			If autoCloseConnection Then SQLConn.Close()

		Catch ex As Exception
			If autoCloseConnection Then SQLConn.Close()
			MsgBox("[Error] Function : Machine.Update" & vbCrLf & ex.Message)
			Return False

		End Try

		Return True

	End Function

	'---------- DELETE ----------'
	Shared Function Delete(ByVal Machine_machine_id As String, Optional SQLConn As MySqlConnection = Nothing) As Boolean

		Dim autoCloseConnection As Boolean = False
		If SQLConn Is Nothing Then
			SQLConn = New MySqlConnection(ConnString)
			SQLConn.Open()
			autoCloseConnection = True
		End If

		Dim CMD As MySqlCommand
		Dim QRY As String

		Try
			QRY = "DELETE FROM" &
						" " & tableName &
						" WHERE machine_id='" & Machine_machine_id & "'"

			CMD = New MySqlCommand(QRY, SQLConn)
			CMD.ExecuteNonQuery()
			If autoCloseConnection Then SQLConn.Close()

		Catch ex As Exception
			If autoCloseConnection Then SQLConn.Close()
			MsgBox("[Error] Function : Machine.Delete" & vbCrLf & ex.Message)
			Return False

		End Try

		Return True

	End Function

	'----- Structure for LIST -----'
	Structure ListItem
		Dim Items() As MachineInfo
		Dim Count As Integer
	End Structure

	'---------- LIST ----------'
	Shared Function List(Optional ByVal Query As String = "", Optional ByVal Condition As String = "", Optional ByVal SortOrder As String = "machine_id", Optional SQLConn As MySqlConnection = Nothing) As ListItem

		If Not Condition = "" Then Condition = " WHERE " & Condition
		If Not SortOrder = "" Then SortOrder = " ORDER BY " & SortOrder

		Dim autoCloseConnection As Boolean = False
		If SQLConn Is Nothing Then
			SQLConn = New MySqlConnection(ConnString)
			SQLConn.Open()
			autoCloseConnection = True
		End If

		Dim CMD As MySqlCommand
		Dim RD As MySqlDataReader
		Dim QRY As String

		Dim ListItemA As ListItem
		Dim MachineInfoA() As MachineInfo = Nothing

		ListItemA.Items = Nothing
		ListItemA.Count = 0

		Try
			If Not Query = "" Then
				QRY = Query
			Else
				QRY = "SELECT *" &
						" FROM " & tableName
			End If
			QRY &= Condition & SortOrder

			CMD = New MySqlCommand(QRY, SQLConn)
			RD = CMD.ExecuteReader
			Dim Ix As Integer = 0
			If RD.HasRows Then

				While RD.Read
					ReDim Preserve MachineInfoA(Ix)

					MachineInfoA(Ix).machine_id = RD!machine_id
					MachineInfoA(Ix).machine_code = RD!machine_code
					MachineInfoA(Ix).machine_name = RD!machine_name
					MachineInfoA(Ix).detail = RD!detail
					MachineInfoA(Ix).remark = RD!remark

					Ix += 1
				End While
			End If

			If autoCloseConnection Then SQLConn.Close()

			ListItemA.Items = MachineInfoA
			ListItemA.Count = Ix

		Catch ex As Exception
			If autoCloseConnection Then SQLConn.Close()
			ListItemA.Count = 0
			MsgBox("[Error] Function : Machine.List" & vbCrLf & ex.Message)

		End Try

		Return ListItemA

	End Function

	'----- Class for TOCOMBOBOXITEMS -----'
	Public Class ComboBoxItems

		Private _DisplayMember As String
		Private _subDisplayMember As String
		Private _ValueMember As String

		Public Overrides Function ToString() As String
			Return _ValueMember
		End Function

		Public Function ToCodeName() As String
			Return _DisplayMember
		End Function

		Public Sub New(ByVal DisplayMember As String, ByVal ValueMember As String)
			_DisplayMember = DisplayMember
			_ValueMember = ValueMember
		End Sub
		Public ReadOnly Property DisplayMember() As String
			Get
				Return _DisplayMember
			End Get
		End Property

		Public ReadOnly Property ValueMember() As String
			Get
				Return _ValueMember
			End Get
		End Property

	End Class

	'---------- TOCOMBOBOXITEMS ----------'
	Shared Function ToComboBoxItems(ByRef RefCMB As ComboBox, DisplayMember As String, ValueMember As String, Optional subDisplayMember As String = "", Optional Delimeter As String = " : ", Optional ByVal Condition As String = "", Optional ByVal SortOrder As String = "machine_id", Optional SQLConn As MySqlConnection = Nothing) As List(Of ComboBoxItems)

		If Not Condition = "" Then Condition = " WHERE " & Condition
		If Not SortOrder = "" Then SortOrder = " ORDER BY " & SortOrder

		Dim autoCloseConnection As Boolean = False
		If SQLConn Is Nothing Then
			SQLConn = New MySqlConnection(ConnString)
			SQLConn.Open()
			autoCloseConnection = True
		End If

		Dim RD As MySqlDataReader
		Dim CMD As MySqlCommand
		Dim QRY As String

		Dim cmbItems = New List(Of ComboBoxItems)

		Try
			QRY = "SELECT * " &
						" FROM " & tableName &
						" " & Condition &
						" " & SortOrder

			CMD = New MySqlCommand(QRY, SQLConn)
			CMD.CommandTimeout = 30
			RD = CMD.ExecuteReader()

			If RD.HasRows = True Then
				While RD.Read()
					If Not subDisplayMember = "" Then
						Dim DM As String = RD.Item(DisplayMember) & Delimeter & RD.Item(subDisplayMember)
						Dim VM As String = RD.Item(ValueMember)
						cmbItems.Add(New ComboBoxItems(DM, VM))
					Else
						cmbItems.Add(New ComboBoxItems(RD.Item(DisplayMember), RD.Item(ValueMember)))
					End If
				End While
			End If

			If autoCloseConnection Then SQLConn.Close()

		Catch ex As Exception
			If autoCloseConnection Then SQLConn.Close()
			MsgBox("[Error] Function : Machine.ToComboBoxItems" & vbCrLf & ex.Message)

		End Try

		RefCMB.DisplayMember = "DisplayMember"
		RefCMB.ValueMember = "ValueMember"
		RefCMB.DataSource = cmbItems

		Return cmbItems

	End Function

	'---------- TOCLASSINFO ----------'
	Function ToMachineInfo() As MachineInfo

		Dim CI As MachineInfo = Nothing

		CI.machine_id = _machine_id
		CI.machine_code = _machine_code
		CI.machine_name = _machine_name
		CI.detail = _detail
		CI.remark = _remark

		Return CI

	End Function

	'---------- COUNT ----------'
	Shared Function Count(ByVal Condition As String, Optional SQLConn As MySqlConnection = Nothing) As Integer

		Dim autoCloseConnection As Boolean = False
		If SQLConn Is Nothing Then
			SQLConn = New MySqlConnection(ConnString)
			SQLConn.Open()
			autoCloseConnection = True
		End If

		Dim CMD As MySqlCommand
		Dim recCount As Integer = 0
		Dim QRY As String

		Try
			QRY = "SELECT COUNT(machine_id) " &
						" FROM Machine " &
						" WHERE " & Condition

			CMD = New MySqlCommand(QRY, SQLConn)
			recCount = CMD.ExecuteScalar
			If autoCloseConnection Then SQLConn.Close()

		Catch ex As Exception
			If autoCloseConnection Then SQLConn.Close()
			MsgBox("[Error] Function : Machine.Count" & vbCrLf & ex.Message)

		End Try

		Return recCount

	End Function

	'---------- CLEAR TABLE ----------'
	Shared Function ClearTable(Optional SQLConn As MySqlConnection = Nothing) As Boolean

		Dim autoCloseConnection As Boolean = False
		If SQLConn Is Nothing Then
			SQLConn = New MySqlConnection(ConnString)
			SQLConn.Open()
			autoCloseConnection = True
		End If

		Dim CMD As MySqlCommand
		Dim QRY As String

		Try

			QRY = "DELETE FROM" &
					" " & tableName

			CMD = New MySqlCommand(QRY, SQLConn)
			CMD.ExecuteNonQuery()

			QRY = "ALTER TABLE " & tableName & " AUTO_INCREMENT = 0"
			CMD = New MySqlCommand(QRY, SQLConn)
			CMD.ExecuteNonQuery()

			If autoCloseConnection Then SQLConn.Close()

		Catch ex As Exception
			If autoCloseConnection Then SQLConn.Close()
			MsgBox("[Error] Function : Machine.ClearTable" & vbCrLf & ex.Message)
			Return False

		End Try

		Return True

	End Function

#End Region

	'============================== Custom Functions =============================='

#Region "Custom Functions"

	'-----------------------------------------------'
	'---------- ADD CUSTOM FUNCTIONS HERE ----------'
	'-----------------------------------------------'
	'---- DO NOT COPY OR PASTE ON THIS SECTION -----'
	'-----------------------------------------------'




#End Region

End Class
