'###########################################'
'This Class is automatic generated by FeiNz's SQL Class Generator.
'Credit: FeiNz.net [feineriz@live.net]
'###########################################'

Imports System.Drawing
Imports System.IO
Imports MySql.Data.MySqlClient
Imports System.Windows.Forms

'If this line above is shows error, please download
'[MySQL Connector for .NET] from http://dev.mysql.com/downloads/connector/net/
'and import reference to the project.

Public Class Part

'============================== Class Header ==============================

#Region "Class Header"

    Private Shared ConnString As String = "Server=10.13.1.10;Database=PMSys;Uid=dbadmin;Pwd=v9bdko9Nx;"
    Private Shared tableName As String = "Part"

    Private _SQLConn As New MySqlConnection(ConnString)
    Private _CMD As MySqlCommand
    Private _QRY As String

    Shared Function BytesToImage(ByVal ImageBytes() As Byte) As Image

        Dim IMG As Image
        Dim MS As New MemoryStream(ImageBytes)

        IMG = Image.FromStream(MS)
        Return IMG

    End Function

    Shared Function ImageToBytes(ByVal Image As Image) As Byte()

        Dim MS As New MemoryStream
        Dim BT() As Byte

        Image.Save(MS, Image.RawFormat)
        BT = MS.GetBuffer()
        Return BT

    End Function

	Private _part_id As Integer
	Private _part_no As String
	Private _part_name As String
	Private _price As Decimal
	Private _remark As String

	Structure PartInfo
		Dim part_id As Integer
		Dim part_no As String
		Dim part_name As String
		Dim price As Decimal
		Dim remark As String
	End Structure

    Sub New(Part_part_id As String)

        Dim SQLConn As New MySqlConnection(ConnString)
        Dim CMD As MySqlCommand
        Dim RD As MySqlDataReader
        Dim QRY As String

        QRY = "SELECT *" &
					" FROM " & tableName &
					" WHERE part_id = '" & Part_part_id & "'"

        Try
            SQLConn.Open()
            CMD = New MySqlCommand(QRY, SQLConn)
            RD = CMD.ExecuteReader

            If RD.HasRows Then
                While RD.Read
					_part_id = RD!part_id
					_part_no = RD!part_no
					_part_name = RD!part_name
					_price = RD!price
					_remark = RD!remark
                End While
            End If
            SQLConn.Close()

        Catch ex As Exception
            SQLConn.Close()
            MsgBox("[Error] Sub : New" & vbCrLf & ex.Message)

        End Try

    End Sub

#End Region

'============================== Class Properties ==============================

#Region "Class Properties"

    ReadOnly Property part_id As Integer
        Get
            Return _part_id
        End Get
    End Property

    Property part_no As String
        Get
            Return _part_no
        End Get
        Set(ByVal value As String)
            _QRY = "UPDATE " & tableName &
						" SET part_no = '" & value & "'" &
						" WHERE part_id = '" & _part_id & "'"

            Try
                _SQLConn.Open()
                _CMD = New MySqlCommand(_QRY, _SQLConn)
                _CMD.ExecuteNonQuery()
                _SQLConn.Close()

            Catch ex As Exception
                _SQLConn.Close()
                MsgBox("[Error] Property : part_no" & vbCrLf & ex.Message, , "Error")

            End Try

            _part_no = value
        End Set
    End Property

    Property part_name As String
        Get
            Return _part_name
        End Get
        Set(ByVal value As String)
            _QRY = "UPDATE " & tableName &
						" SET part_name = '" & value & "'" &
						" WHERE part_id = '" & _part_id & "'"

            Try
                _SQLConn.Open()
                _CMD = New MySqlCommand(_QRY, _SQLConn)
                _CMD.ExecuteNonQuery()
                _SQLConn.Close()

            Catch ex As Exception
                _SQLConn.Close()
                MsgBox("[Error] Property : part_name" & vbCrLf & ex.Message, , "Error")

            End Try

            _part_name = value
        End Set
    End Property

    Property price As Decimal
        Get
            Return _price
        End Get
        Set(ByVal value As Decimal)
            _QRY = "UPDATE " & tableName &
						" SET price = '" & value & "'" &
						" WHERE part_id = '" & _part_id & "'"

            Try
                _SQLConn.Open()
                _CMD = New MySqlCommand(_QRY, _SQLConn)
                _CMD.ExecuteNonQuery()
                _SQLConn.Close()

            Catch ex As Exception
                _SQLConn.Close()
                MsgBox("[Error] Property : price" & vbCrLf & ex.Message, , "Error")

            End Try

            _price = value
        End Set
    End Property

    Property remark As String
        Get
            Return _remark
        End Get
        Set(ByVal value As String)
            _QRY = "UPDATE " & tableName &
						" SET remark = '" & value & "'" &
						" WHERE part_id = '" & _part_id & "'"

            Try
                _SQLConn.Open()
                _CMD = New MySqlCommand(_QRY, _SQLConn)
                _CMD.ExecuteNonQuery()
                _SQLConn.Close()

            Catch ex As Exception
                _SQLConn.Close()
                MsgBox("[Error] Property : remark" & vbCrLf & ex.Message, , "Error")

            End Try

            _remark = value
        End Set
    End Property

#End Region

'============================== Required Function ==============================

#Region "Required Function"

    Shared Function Add(ByVal PartInfoA As PartInfo) As Boolean

        Dim SQLConn As New MySqlConnection(ConnString)
        Dim CMD As MySqlCommand
        Dim QRY As String

        QRY = "INSERT INTO " & tableName & "(part_id, part_no, part_name, price, remark)" &
					" VALUES(@part_id, @part_no, @part_name, @price, @remark)"

        Try
            SQLConn.Open()
            CMD = New MySqlCommand(QRY, SQLConn)

			CMD.Parameters.AddWithValue("@part_id", PartInfoA.part_id)
			CMD.Parameters.AddWithValue("@part_no", PartInfoA.part_no)
			CMD.Parameters.AddWithValue("@part_name", PartInfoA.part_name)
			CMD.Parameters.AddWithValue("@price", PartInfoA.price)
			CMD.Parameters.AddWithValue("@remark", PartInfoA.remark)

            CMD.ExecuteNonQuery()
            SQLConn.Close()

        Catch ex As Exception
            SQLConn.Close()
            MsgBox("[Error] Function : Add" & vbCrLf & ex.Message)
            Return False

        End Try

        Return True

    End Function

    Shared Function Delete(ByVal Part_part_id As String) As Boolean

        Dim SQLConn As New MySqlConnection(ConnString)
        Dim CMD As MySqlCommand
        Dim QRY As String
		
        QRY = "DELETE FROM" &
					" " & tableName & 
					" WHERE part_id='" & Part_part_id & "'"

        Try
            SQLConn.Open()
            CMD = New MySqlCommand(QRY, SQLConn)
            CMD.ExecuteNonQuery()
            SQLConn.Close()

        Catch ex As Exception
            SQLConn.Close()
            MsgBox("[Error] Function : Delete" & vbCrLf & ex.Message)
            Return False

        End Try

        Return True

    End Function

'------------------------------ List Property ------------------------------

    Structure ListItem
        Dim Items() As PartInfo
        Dim Count As Integer
    End Structure

    Shared Function List(Optional ByVal Condition As String = "", Optional ByVal SortOrder As String = "part_id") As ListItem

        If Not Condition = "" Then Condition = " WHERE " & Condition
        If Not SortOrder = "" Then SortOrder = " ORDER BY " & SortOrder

        Dim SQLConn As New MySqlConnection(ConnString)
        Dim CMD As MySqlCommand
        Dim RD As MySqlDataReader
        Dim QRY As String

        Dim ListItemA As ListItem
        Dim PartInfoA() As PartInfo = Nothing

        ListItemA.Items = Nothing
        ListItemA.Count = 0

        QRY = "SELECT *" &
					" FROM " & tableName &
					" " & Condition &
					" " & SortOrder

        Try
            SQLConn.Open()
            CMD = New MySqlCommand(QRY, SQLConn)
            RD = CMD.ExecuteReader
            Dim Ix As Integer = 0
            If RD.HasRows Then

                While RD.Read
                    ReDim Preserve PartInfoA(Ix)

					PartInfoA(Ix).part_id = RD!part_id
					PartInfoA(Ix).part_no = RD!part_no
					PartInfoA(Ix).part_name = RD!part_name
					PartInfoA(Ix).price = RD!price
					PartInfoA(Ix).remark = RD!remark

                    Ix += 1
                End While
            End If

            SQLConn.Close()

            ListItemA.Items = PartInfoA
            ListItemA.Count = Ix

        Catch ex As Exception
            SQLConn.Close()
            ListItemA.Count = 0
            MsgBox("[Error] Function : List" & vbCrLf & ex.Message)

        End Try

        Return ListItemA

    End Function

    Public Class ComboBoxItems

        Private _DisplayMember As String
        Private _subDisplayMember As String
        Private _ValueMember As String

        Public Overrides Function ToString() As String
            Return _ValueMember
        End Function

        Public Function ToCodeName() As String
            Return _DisplayMember
        End Function

        Public Sub New(ByVal DisplayMember As String, ByVal ValueMember As String)
            _DisplayMember = DisplayMember
            _ValueMember = ValueMember
        End Sub
        Public ReadOnly Property DisplayMember() As String
            Get
                Return _DisplayMember
            End Get
        End Property

        Public ReadOnly Property ValueMember() As String
            Get
                Return _ValueMember
            End Get
        End Property

    End Class

    Shared Function ToComboBoxItems(ByRef RefCMB As ComboBox, DisplayMember As String, ValueMember As String, Optional subDisplayMember As String = "", Optional Delimeter As String = " : ", Optional ByVal Condition As String = "", Optional ByVal SortOrder As String = "ID") As List(Of ComboBoxItems)

        If Not Condition = "" Then Condition = " WHERE " & Condition
        If Not SortOrder = "" Then SortOrder = " ORDER BY " & SortOrder

        Dim SQLConn As New MySqlConnection(ConnString)
        Dim RD As MySqlDataReader
        Dim CMD As MySqlCommand
        Dim QRY As String

        Dim cmbItems = New List(Of ComboBoxItems)

        QRY = "SELECT * " &
                    " FROM " & tableName &
                    " " & Condition &
                    " " & SortOrder

        Try
            SQLConn.Open()
            CMD = New MySqlCommand(QRY, SQLConn)
            CMD.CommandTimeout = 30
            RD = CMD.ExecuteReader()

            If RD.HasRows = True Then
                While RD.Read()
                    If Not subDisplayMember = "" Then
                        Dim DM As String = RD.Item(DisplayMember) & Delimeter & RD.Item(subDisplayMember)
                        Dim VM As String = RD.Item(ValueMember)
                        cmbItems.Add(New ComboBoxItems(DM, VM))
                    Else
                        cmbItems.Add(New ComboBoxItems(RD.Item(DisplayMember), RD.Item(ValueMember)))
                    End If
                End While
            End If

            SQLConn.Close()

        Catch ex As Exception
            SQLConn.Close()
            MsgBox("[Error] Function : ToComboBoxItems" & vbCrLf & ex.Message)

        End Try

        RefCMB.DisplayMember = "DisplayMember"
        RefCMB.ValueMember = "ValueMember"
				RefCMB.DataSource = cmbItems

        Return cmbItems

    End Function

    Function ToPartInfo() As PartInfo

        Dim CI As PartInfo = Nothing

		CI.part_id = _part_id
		CI.part_no = _part_no
		CI.part_name = _part_name
		CI.price = _price
		CI.remark = _remark

        Return CI

    End Function

    Shared Function Count(ByVal Condition As String) As Integer

        Dim DBConn As New MySqlConnection(ConnString)
        Dim CMD As MySqlCommand
        Dim recCount As Integer = 0
        Dim QRY As String

        QRY = "SELECT COUNT(ID) " & _
					" FROM Part " & _
					" WHERE " & Condition
        Try
            DBConn.Open()
            CMD = New MySqlCommand(QRY, DBConn)
            recCount = CMD.ExecuteScalar
            DBConn.Close()

        Catch ex As Exception
            DBConn.Close()
			MsgBox("[Error] Function : Count" & vbCrLf & ex.Message)

        End Try

        Return recCount

    End Function

#End Region

'============================== Extra Function ==============================

#Region "Extra Function"

    Structure IsExistInfo
        Dim Value As Boolean
        Dim Items() As String
        Dim Count As Integer
        Dim Err As Boolean
    End Structure

    Shared Function IsExist(ByVal contentString As String, Optional ByVal columnName As String = "part_id") As IsExistInfo

        Dim DBConn As New MySqlConnection(ConnString)
        Dim CMD As MySqlCommand
        Dim RD As MySqlDataReader
        Dim QRY As String

        Dim IsExistInfoA As IsExistInfo
        IsExistInfoA.Value = True
        IsExistInfoA.Items = Nothing
        IsExistInfoA.Err = False

        Dim Items() As String = Nothing
        Dim I As Integer = 0

        QRY = "SELECT part_id" &
					" FROM " & tableName &
					" WHERE " & columnName & "='" & contentString & "'"

        Try
            DBConn.Open()
            CMD = New MySqlCommand(QRY, DBConn)
            RD = CMD.ExecuteReader
            DBConn.Close()

            If RD.HasRows Then
                IsExistInfoA.Value = True
                While RD.Read
                    ReDim Preserve Items(I)
                    Items(I) = RD!part_id
                    I += 1
				End While
            End If

            IsExistInfoA.Items = Items
            IsExistInfoA.Count = I

        Catch ex As Exception
            DBConn.Close()
            MsgBox("[Error] Function : IsExist" & vbCrLf & ex.Message)
			IsExistInfoA.Err = True
            Return IsExistInfoA

        End Try

        DBConn.Close()
        Return IsExistInfoA

    End Function



#End Region

End Class
